services:
  frontend:
    volumes:
      - ./dashboard-ui:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ./dashboard-ui/.env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run dev

  backend:
    depends_on:
       db:
         condition: service_healthy
    environment:
      - ENV=development

  db:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "atriva", "-d", "atrv-retail"]
      interval: 3s
      timeout: 5s
      retries: 5
