services:
  frontend:
    build:
      context: ./dashboard-ui
      args:
        NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    ports:
      - "3000:3000"
    volumes:
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - retail-net

  backend:
    build:
      context: ./dashboard-backend
    env_file:
      - ./dashboard-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - retail-net

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./dashboard-backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - retail-net

  ai_inference:
    build: ./services/ai-inference
    ports:
      - "8001:8001"
    env_file:
      - ./services/ai-inference/.env
    volumes:
      - shared-temp-data:/app/shared
    networks:
      - retail-net

  video_pipeline:
    build: ./services/video-pipeline
    ports:
      - "8002:8002"
    env_file:
      - ./services/video-pipeline/.env
    volumes:
      - shared-temp-data:/app/shared
    networks:
      - retail-net

  #analytics_engine:
  #  build: ./services/analytics-engine
  #  ports:
  #    - "8003:8003"
  #  networks:
  #    - retail-net

volumes:
  pgdata:
  shared-temp-data:
  frontend_node_modules:

networks:
  retail-net:
    driver: bridge