services:
  frontend:
    build:
      args:
        - NEXT_PUBLIC_API_URL=http://localhost
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost
    volumes:
      - ./dashboard-ui:/app
      - frontend_next:/app/.next
    command: npm run dev

  backend:
    environment:
      - ENV=development
    depends_on:
      - video_pipeline
      - ai_inference

  ai_inference:
    volumes:
      - shared-frames-data:/app/frames

  video_pipeline:
    volumes:
      - shared-frames-data:/app/frames

volumes:
  shared-frames-data:
  frontend_next: 