services:
  frontend:
    build:
      context: ./dashboard-ui
      args:
        - NEXT_PUBLIC_API_URL=http://localhost/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost/api
    volumes:
      - ./dashboard-ui:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - backend
    networks:
      - retail-net
    command: npm run dev

  backend:
    build:
      context: ./dashboard-backend
    env_file:
      - ./dashboard-backend/.env
    environment:
      - ENV=development
      - VIDEO_PIPELINE_URL=http://video_pipeline:8002
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      video_pipeline:
        condition: service_healthy
      ai_inference:
        condition: service_healthy
    networks:
      - retail-net

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./dashboard-backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - retail-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atriva -d atrv-retail"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  ai_inference:
    build: ./services/ai-inference
    ports:
      - "8001:8001"
    env_file:
      - ./services/ai-inference/.env
    volumes:
      - shared-temp-data:/app/shared
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - retail-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  video_pipeline:
    build: ./services/video-pipeline
    ports:
      - "8002:8002"
    env_file:
      - ./services/video-pipeline/.env
    volumes:
      - shared-temp-data:/app/shared
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - retail-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/v1/video-pipeline/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - video_pipeline
      - ai_inference
    networks:
      - retail-net

volumes:
  pgdata:
  shared-temp-data:
  frontend_node_modules:
  frontend_next:

networks:
  retail-net:
    driver: bridge